version: '3.8'

services:

  backend:
    build:
      context: .
    image: appmern/backend:latest
    
    ports:
      - "5032:5032"
    environment:
      - PORT=5032
      - MONGO_DB_URI=mongodb://root:1234@db:27017/elearning?authSource=admin&replicaSet=rs0
    volumes:
      - app:/app
    depends_on:
      - db
    restart: always

  db:
    image: appmern/mongo:v1
    restart: always
    
    
    

  mongo-express:
    image: appmern/mongo-express:v2
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@db:27017/  # Use db:27017 for internal connection
    depends_on:
      - db
      
# Define named volumes
volumes:
  mongo-data:
    driver: local
  app:  # Declare the app volume here
    driver: local  # You can specify the driver, but the default is "local"
