version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "5032:5032"
    environment:
      PORT: 5032
      MONGO_DB_URI: mongodb://root:1234@db:27017/elearning?authSource=admin
    volumes:
      - app:/app
    depends_on:
      - db

  db:
    image: mongo:4.0.28
    restart: always
    ports:
      - "5021:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo-data:/data/db
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@db:27017/

volumes:
  mongo-data:
    driver: local
  app:
    driver: local